[workspace]
members = [
    "bin",
    "birdeye",
    "defi/raydium-amm-types",
    "dexscreener-api",
    "jupiter-interface-types",
    "tx-parse-types",
    "vybe-api",
    "vybe-api/types",
]
resolver = "2"
