[package]
name = "vybe-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
anyhow = "1"
vybe-api-types = { path = "./types" }
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
