[package]
name = "birdeye"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
reqwest = "0.12.4"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.60"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full"] }
