[package]
name = "tx-parse-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
solana-program = "1.18.14"
solana-sdk = "1.18.14"
solana-transaction-status = "1.18.14"
